#!/bin/bash

# title           : h2i - homematic two influx
# description     : Pull data from homematic ccu via xmlapi and stores them inside a time series database like influxdb.
# author          : Torsten Scholz (https://github.com/TorstenScholz/h2i)
# License         : GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
# date            : 05.02.2023
# version         : 1.2.5
# usage           : h2i [command] [option]
# notes           : Linux tools: xmllint, curl, awk, cut and sed must be installed.

# Settings
ccudata="/tmp/homematic.data"                                 # Path and filename for ccu.data file
statelist="/tmp/statelist.xml"                                # Path and filename for statelist.xml file
ccu="http://homematic/addons/xmlapi/statelist.cgi"            # URL where statelist.xml can be pulled from
db_user="admin"                                               # User of influxdb
db_pass="*********"                                           # Passord of influxdb
db_url="http://localhost:8086/write?db=h2i"                   # URL of influxdb with port and database 

# List of ise_ids and values to parse from statelist.xml
# FORMAT: ise_id,type1,type2,type3,...
# EXAMPLE: 6456,SET_TEMPERATURE,ACTUAL_TEMPERATURE,VALVE_STATE,BATTERY_STATE
# HINT: No empty line at the beginnig or end. First the ID then the values separated by commas.

list_of_ids="6123,SET_TEMPERATURE,ACTUAL_TEMPERATURE,ACTUAL_HUMIDITY,BATTERY_STATE,LOWBAT
2469,SET_TEMPERATURE,ACTUAL_TEMPERATURE,VALVE_STATE,BATTERY_STATE,LOWBAT
3564,ENERGY_COUNTER,POWER,CURRENT,VOLTAGE,FREQUENCY,STATE
7846,ACTUAL_TEMPERATURE,HUMIDITY,ILLUMINATION,RAIN_COUNTER,SUNSHINEDURATION,WIND_DIR,WIND_DIR_RANGE,WIND_SPEED,LOW_BAT
6185,STATE,LOWBAT"


# No need to change anything below this line.


# Define Variables
PROGRAM="h2i"
VERSION="1.2.2"
error=""


# Set Enviroment
xmllint=`command -v xmllint` || { echo "I require 'xmllint' but it's not installed. Use your package manager to install it or visit 'http://www.xmlsoft.org'. Aborting."; exit 1; }
curl=`command -v curl` || { echo "I require 'curl' but it's not installed. Use your package manager to install it or visit 'https://curl.se'. Aborting."; exit 1; }
awk=`command -v awk` || { echo "I require 'awk' but it's not installed. Use your package manager to install it. Aborting."; exit 1; }
cut=`command -v cut` || { echo "I require 'cut' but it's not installed. Use your package manager to install it. Aborting."; exit 1; }
sed=`command -v sed` || { echo "I require 'sed' but it's not installed. Use your package manager to install it. Aborting."; exit 1; }
echo -n "" > $ccudata


# Function: Get statelist.xml
get_statelist () {

  # Test if connection to ccu can be made
  if ! $curl -s --head --connect-timeout 1 $ccu | grep "200" > /dev/null; then
    # No connection to ccu 
    echo ""
    echo "ERROR: Connection to $ccu not possible. Verify that address of ccu is correct and reachable."
    exit 1

  else
    # connect to ccu und get statelist
    $curl -s $ccu -o $statelist
  fi
}


# Function: Parsing XML data
parse_xml () {
  device_id=$1
  device_type=$2
  xpath="(//device[@ise_id="$device_id"]/channel/datapoint[@type='$device_type'])[1]"

  # Test if device and type exist in xml
  if ! $xmllint --xpath //device[@ise_id="$device_id"] $statelist > /dev/null 2>&1; then
    # Device not found in xml
    echo ""
    echo "ERROR: Device name: "$device_id" not found in xml"
    exit 1

  elif ! $xmllint --xpath $xpath "$statelist" > /dev/null 2>&1; then
    # Type not found in xml
    echo ""
    echo "ERROR: Device type: "$device_type" not found in xml"
    exit 1

  else
    # Parse data into variables 
    name=`$xmllint --xpath //device[@ise_id="$device_id"] "$statelist" | $awk -F= '$1=="name"{print $2}' RS=' ' | $sed -n "1p"  | $sed 's/^"//;s/"$//'`
    id=`xmllint --xpath $xpath "$statelist" | awk -F= '$1=="ise_id"{print $2}' RS=' ' | sed 's/^"//;s/"$//'`
    channel=`$xmllint --xpath //datapoint[@ise_id="$id"] "$statelist" | $awk -F= '$1=="name"{print $2}' RS=' ' | $cut -d ":" -f 2 | $cut -d "." -f 1`
    serial=`$xmllint --xpath //datapoint[@ise_id="$id"] "$statelist" | $awk -F= '$1=="name"{print $2}' RS=' ' | $cut -d ":" -f 1 | $cut -d "." -f 2`
    type=`$xmllint --xpath //datapoint[@ise_id="$id"] "$statelist" | $awk -F= '$1=="name"{print $2}' RS=' ' | $cut -d ":" -f 2 | $cut -d "." -f 2 | $sed 's/^"//;s/"$//'`
    value=`$xmllint --xpath //datapoint[@ise_id="$id"] "$statelist" | $awk -F= '$1=="value"{print $2}' RS=' ' | $sed 's/^"//;s/"$//'`


    # Convert boolean values 
    if [ "$value" = "false" ]; then
      value="0"
    elif [ "$value" = "true" ]; then
      value="1"
    fi 


    # Write data to ccudata file
    echo "homematic=ccu1,name=$name,channel=$channel,serial=$serial,ise_id=$id,type=$type value=$value" >> $ccudata
  fi
}


# Main Loop
# Get comand + option and work accordingly
COMMAND="$1"
OPTION="$2"

case $COMMAND in
  version | -v | --version)
    echo "$PROGRAM $VERSION"
  ;;

  pull | -p | --pull)
    # Start time measurement
    start=$(date +%s)  


    # Get statelist from ccu
    echo -n "Receiving statelist.xml... "
    get_statelist
    echo "done"


    # Get data from id.list
    echo -n "Parsing data"
    devices=`echo "$list_of_ids" | $sed $= -n`


    # Read list of IDs and call xml parser with device id and given element
    while read LINE; do
      IFS=','
      read -r -a array_of_ids <<< "$LINE"
      id_from_list="${array_of_ids[0]}"
      for element_from_list in "${array_of_ids[@]:1}"; do
        parse_xml $id_from_list $element_from_list
        echo -n "."
      done
    done <<< $(echo "$list_of_ids")
    echo " done"


    # Store data in time series database
    echo -n "Writing to influxDB... "
    $curl -s -i -XPOST -u $db_user:$db_pass "$db_url" --data-binary @$ccudata > /dev/null 
    echo "done"


    # Calculate devices, values and needed time
    values=`$sed $= -n $ccudata`
    end=$(date +%s)
    echo "Computed: "$devices "devices with: "$values "values in: "$((end - $start)) "seconds"


    # Debug option
    if [ "$OPTION" = "debug" ]; then
      echo ""
      echo "DEBUG INFO:"
      cat $ccudata
    fi

    echo "No error"
  ;;

  *)
    echo "$PROGRAM v$VERSION"
    echo " Pulls data from a homematic ccu via xmlapi and stores them inside a time series database like influxdb."
    echo " Configuration is done inside this script."
    echo ""
    echo "Usage:"
    echo " $PROGRAM [command] [option]"
    echo ""
    echo "Available Commands:"
    echo " version        Print version information"
    echo " help           Print this help message"
    echo " pull           Gets values from given device ids"
    echo ""
    echo "Available Options:"
    echo " debug          Enables Debug informations"
  ;;
esac

# Clean up
rm $statelist

unset PROGRAM
unset VERSION
unset error
unset ccudata
unset statelist
unset ccu
unset db_user
unset db_pass
unset db_url
unset xmllint
unset curl
unset awk
unset cut
unset sed
unset list_of_ids
unset device_id
unset device_type
unset xpath
unset name
unset id
unset channel
unset serial
unset type
unset value
unset COMMAND
unset OPTION
unset start
unset devices
unset IFS
unset array_of_ids
unset id_from_list
unset element_from_list
unset values
unset end


# Exit
exit 0